/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MasterRouteImport } from './routes/master'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as DesafioRouteImport } from './routes/desafio'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterIndexRouteImport } from './routes/master.index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OnboardingCompanyRouteImport } from './routes/onboarding.company'
import { Route as MasterTrafegoRouteImport } from './routes/master.trafego'
import { Route as MasterSuporteRouteImport } from './routes/master.suporte'
import { Route as MasterRenovacoesRouteImport } from './routes/master.renovacoes'
import { Route as MasterPlanosRouteImport } from './routes/master.planos'
import { Route as MasterPagamentosRouteImport } from './routes/master.pagamentos'
import { Route as MasterInadimplentesRouteImport } from './routes/master.inadimplentes'
import { Route as MasterEmpresasRouteImport } from './routes/master.empresas'
import { Route as MasterCuponsRouteImport } from './routes/master.cupons'
import { Route as MasterConfiguracoesRouteImport } from './routes/master.configuracoes'
import { Route as MasterAssinaturasRouteImport } from './routes/master.assinaturas'
import { Route as DemoBarbeariaRouteImport } from './routes/demo.barbearia'
import { Route as BillingSuccessRouteImport } from './routes/billing.success'
import { Route as BillingPlansRouteImport } from './routes/billing.plans'
import { Route as BillingCheckoutRouteImport } from './routes/billing.checkout'
import { Route as BillingCancelRouteImport } from './routes/billing.cancel'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AgendarSlugRouteImport } from './routes/agendar.$slug'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as AdminServicosRouteImport } from './routes/admin.servicos'
import { Route as AdminRepassesRouteImport } from './routes/admin.repasses'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminPlanoRouteImport } from './routes/admin.plano'
import { Route as AdminListaEsperaRouteImport } from './routes/admin.lista-espera'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminEquipeRouteImport } from './routes/admin.equipe'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminComandasRouteImport } from './routes/admin.comandas'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as AdminAppRouteImport } from './routes/admin.app'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'
import { Route as ConvitePrestadorTokenRouteImport } from './routes/convite.prestador.$token'
import { Route as AdminPlanoCheckoutRouteImport } from './routes/admin.plano.checkout'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafioRoute = DesafioRouteImport.update({
  id: '/desafio',
  path: '/desafio',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterIndexRoute = MasterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MasterRoute,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OnboardingCompanyRoute = OnboardingCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => OnboardingRoute,
} as any)
const MasterTrafegoRoute = MasterTrafegoRouteImport.update({
  id: '/trafego',
  path: '/trafego',
  getParentRoute: () => MasterRoute,
} as any)
const MasterSuporteRoute = MasterSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => MasterRoute,
} as any)
const MasterRenovacoesRoute = MasterRenovacoesRouteImport.update({
  id: '/renovacoes',
  path: '/renovacoes',
  getParentRoute: () => MasterRoute,
} as any)
const MasterPlanosRoute = MasterPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => MasterRoute,
} as any)
const MasterPagamentosRoute = MasterPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => MasterRoute,
} as any)
const MasterInadimplentesRoute = MasterInadimplentesRouteImport.update({
  id: '/inadimplentes',
  path: '/inadimplentes',
  getParentRoute: () => MasterRoute,
} as any)
const MasterEmpresasRoute = MasterEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => MasterRoute,
} as any)
const MasterCuponsRoute = MasterCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => MasterRoute,
} as any)
const MasterConfiguracoesRoute = MasterConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => MasterRoute,
} as any)
const MasterAssinaturasRoute = MasterAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => MasterRoute,
} as any)
const DemoBarbeariaRoute = DemoBarbeariaRouteImport.update({
  id: '/barbearia',
  path: '/barbearia',
  getParentRoute: () => DemoRoute,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingPlansRoute = BillingPlansRouteImport.update({
  id: '/billing/plans',
  path: '/billing/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCheckoutRoute = BillingCheckoutRouteImport.update({
  id: '/billing/checkout',
  path: '/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCancelRoute = BillingCancelRouteImport.update({
  id: '/billing/cancel',
  path: '/billing/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarSlugRoute = AgendarSlugRouteImport.update({
  id: '/agendar/$slug',
  path: '/agendar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicosRoute = AdminServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRepassesRoute = AdminRepassesRouteImport.update({
  id: '/repasses',
  path: '/repasses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanoRoute = AdminPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListaEsperaRoute = AdminListaEsperaRouteImport.update({
  id: '/lista-espera',
  path: '/lista-espera',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipeRoute = AdminEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComandasRoute = AdminComandasRouteImport.update({
  id: '/comandas',
  path: '/comandas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppRoute = AdminAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const ConvitePrestadorTokenRoute = ConvitePrestadorTokenRouteImport.update({
  id: '/convite/prestador/$token',
  path: '/convite/prestador/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlanoCheckoutRoute = AdminPlanoCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AdminPlanoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/cliente': typeof ClienteRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRouteWithChildren
  '/desafio': typeof DesafioRoute
  '/entrar': typeof EntrarRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pagamento': typeof PagamentoRoute
  '/planos': typeof PlanosRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/app': typeof AdminAppRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/comandas': typeof AdminComandasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/lista-espera': typeof AdminListaEsperaRoute
  '/admin/plano': typeof AdminPlanoRouteWithChildren
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/repasses': typeof AdminRepassesRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/billing/plans': typeof BillingPlansRoute
  '/billing/success': typeof BillingSuccessRoute
  '/demo/barbearia': typeof DemoBarbeariaRoute
  '/master/assinaturas': typeof MasterAssinaturasRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/cupons': typeof MasterCuponsRoute
  '/master/empresas': typeof MasterEmpresasRoute
  '/master/inadimplentes': typeof MasterInadimplentesRoute
  '/master/pagamentos': typeof MasterPagamentosRoute
  '/master/planos': typeof MasterPlanosRoute
  '/master/renovacoes': typeof MasterRenovacoesRoute
  '/master/suporte': typeof MasterSuporteRoute
  '/master/trafego': typeof MasterTrafegoRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/admin/': typeof AdminIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/master/': typeof MasterIndexRoute
  '/admin/plano/checkout': typeof AdminPlanoCheckoutRoute
  '/convite/prestador/$token': typeof ConvitePrestadorTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/cliente': typeof ClienteRoute
  '/dashboard': typeof DashboardRoute
  '/desafio': typeof DesafioRoute
  '/entrar': typeof EntrarRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pagamento': typeof PagamentoRoute
  '/planos': typeof PlanosRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/app': typeof AdminAppRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/comandas': typeof AdminComandasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/lista-espera': typeof AdminListaEsperaRoute
  '/admin/plano': typeof AdminPlanoRouteWithChildren
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/repasses': typeof AdminRepassesRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/billing/plans': typeof BillingPlansRoute
  '/billing/success': typeof BillingSuccessRoute
  '/demo/barbearia': typeof DemoBarbeariaRoute
  '/master/assinaturas': typeof MasterAssinaturasRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/cupons': typeof MasterCuponsRoute
  '/master/empresas': typeof MasterEmpresasRoute
  '/master/inadimplentes': typeof MasterInadimplentesRoute
  '/master/pagamentos': typeof MasterPagamentosRoute
  '/master/planos': typeof MasterPlanosRoute
  '/master/renovacoes': typeof MasterRenovacoesRoute
  '/master/suporte': typeof MasterSuporteRoute
  '/master/trafego': typeof MasterTrafegoRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/admin': typeof AdminIndexRoute
  '/demo': typeof DemoIndexRoute
  '/master': typeof MasterIndexRoute
  '/admin/plano/checkout': typeof AdminPlanoCheckoutRoute
  '/convite/prestador/$token': typeof ConvitePrestadorTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/checkout': typeof CheckoutRoute
  '/cliente': typeof ClienteRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRouteWithChildren
  '/desafio': typeof DesafioRoute
  '/entrar': typeof EntrarRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pagamento': typeof PagamentoRoute
  '/planos': typeof PlanosRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/app': typeof AdminAppRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/comandas': typeof AdminComandasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/lista-espera': typeof AdminListaEsperaRoute
  '/admin/plano': typeof AdminPlanoRouteWithChildren
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/repasses': typeof AdminRepassesRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/billing/plans': typeof BillingPlansRoute
  '/billing/success': typeof BillingSuccessRoute
  '/demo/barbearia': typeof DemoBarbeariaRoute
  '/master/assinaturas': typeof MasterAssinaturasRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/cupons': typeof MasterCuponsRoute
  '/master/empresas': typeof MasterEmpresasRoute
  '/master/inadimplentes': typeof MasterInadimplentesRoute
  '/master/pagamentos': typeof MasterPagamentosRoute
  '/master/planos': typeof MasterPlanosRoute
  '/master/renovacoes': typeof MasterRenovacoesRoute
  '/master/suporte': typeof MasterSuporteRoute
  '/master/trafego': typeof MasterTrafegoRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/admin/': typeof AdminIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/master/': typeof MasterIndexRoute
  '/admin/plano/checkout': typeof AdminPlanoCheckoutRoute
  '/convite/prestador/$token': typeof ConvitePrestadorTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/checkout'
    | '/cliente'
    | '/dashboard'
    | '/demo'
    | '/desafio'
    | '/entrar'
    | '/forgot-password'
    | '/login'
    | '/master'
    | '/onboarding'
    | '/pagamento'
    | '/planos'
    | '/plans'
    | '/register'
    | '/reset-password'
    | '/admin/agenda'
    | '/admin/app'
    | '/admin/branding'
    | '/admin/clientes'
    | '/admin/comandas'
    | '/admin/configuracoes'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/lista-espera'
    | '/admin/plano'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/repasses'
    | '/admin/servicos'
    | '/admin/whatsapp'
    | '/agendar/$slug'
    | '/auth/callback'
    | '/billing/cancel'
    | '/billing/checkout'
    | '/billing/plans'
    | '/billing/success'
    | '/demo/barbearia'
    | '/master/assinaturas'
    | '/master/configuracoes'
    | '/master/cupons'
    | '/master/empresas'
    | '/master/inadimplentes'
    | '/master/pagamentos'
    | '/master/planos'
    | '/master/renovacoes'
    | '/master/suporte'
    | '/master/trafego'
    | '/onboarding/company'
    | '/admin/'
    | '/demo/'
    | '/master/'
    | '/admin/plano/checkout'
    | '/convite/prestador/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/checkout'
    | '/cliente'
    | '/dashboard'
    | '/desafio'
    | '/entrar'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/pagamento'
    | '/planos'
    | '/plans'
    | '/register'
    | '/reset-password'
    | '/admin/agenda'
    | '/admin/app'
    | '/admin/branding'
    | '/admin/clientes'
    | '/admin/comandas'
    | '/admin/configuracoes'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/lista-espera'
    | '/admin/plano'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/repasses'
    | '/admin/servicos'
    | '/admin/whatsapp'
    | '/agendar/$slug'
    | '/auth/callback'
    | '/billing/cancel'
    | '/billing/checkout'
    | '/billing/plans'
    | '/billing/success'
    | '/demo/barbearia'
    | '/master/assinaturas'
    | '/master/configuracoes'
    | '/master/cupons'
    | '/master/empresas'
    | '/master/inadimplentes'
    | '/master/pagamentos'
    | '/master/planos'
    | '/master/renovacoes'
    | '/master/suporte'
    | '/master/trafego'
    | '/onboarding/company'
    | '/admin'
    | '/demo'
    | '/master'
    | '/admin/plano/checkout'
    | '/convite/prestador/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/checkout'
    | '/cliente'
    | '/dashboard'
    | '/demo'
    | '/desafio'
    | '/entrar'
    | '/forgot-password'
    | '/login'
    | '/master'
    | '/onboarding'
    | '/pagamento'
    | '/planos'
    | '/plans'
    | '/register'
    | '/reset-password'
    | '/admin/agenda'
    | '/admin/app'
    | '/admin/branding'
    | '/admin/clientes'
    | '/admin/comandas'
    | '/admin/configuracoes'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/lista-espera'
    | '/admin/plano'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/repasses'
    | '/admin/servicos'
    | '/admin/whatsapp'
    | '/agendar/$slug'
    | '/auth/callback'
    | '/billing/cancel'
    | '/billing/checkout'
    | '/billing/plans'
    | '/billing/success'
    | '/demo/barbearia'
    | '/master/assinaturas'
    | '/master/configuracoes'
    | '/master/cupons'
    | '/master/empresas'
    | '/master/inadimplentes'
    | '/master/pagamentos'
    | '/master/planos'
    | '/master/renovacoes'
    | '/master/suporte'
    | '/master/trafego'
    | '/onboarding/company'
    | '/admin/'
    | '/demo/'
    | '/master/'
    | '/admin/plano/checkout'
    | '/convite/prestador/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CheckoutRoute: typeof CheckoutRoute
  ClienteRoute: typeof ClienteRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRouteWithChildren
  DesafioRoute: typeof DesafioRoute
  EntrarRoute: typeof EntrarRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MasterRoute: typeof MasterRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PagamentoRoute: typeof PagamentoRoute
  PlanosRoute: typeof PlanosRoute
  PlansRoute: typeof PlansRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AgendarSlugRoute: typeof AgendarSlugRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BillingCancelRoute: typeof BillingCancelRoute
  BillingCheckoutRoute: typeof BillingCheckoutRoute
  BillingPlansRoute: typeof BillingPlansRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
  ConvitePrestadorTokenRoute: typeof ConvitePrestadorTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafio': {
      id: '/desafio'
      path: '/desafio'
      fullPath: '/desafio'
      preLoaderRoute: typeof DesafioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/': {
      id: '/master/'
      path: '/'
      fullPath: '/master/'
      preLoaderRoute: typeof MasterIndexRouteImport
      parentRoute: typeof MasterRoute
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/onboarding/company': {
      id: '/onboarding/company'
      path: '/company'
      fullPath: '/onboarding/company'
      preLoaderRoute: typeof OnboardingCompanyRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/master/trafego': {
      id: '/master/trafego'
      path: '/trafego'
      fullPath: '/master/trafego'
      preLoaderRoute: typeof MasterTrafegoRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/suporte': {
      id: '/master/suporte'
      path: '/suporte'
      fullPath: '/master/suporte'
      preLoaderRoute: typeof MasterSuporteRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/renovacoes': {
      id: '/master/renovacoes'
      path: '/renovacoes'
      fullPath: '/master/renovacoes'
      preLoaderRoute: typeof MasterRenovacoesRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/planos': {
      id: '/master/planos'
      path: '/planos'
      fullPath: '/master/planos'
      preLoaderRoute: typeof MasterPlanosRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/pagamentos': {
      id: '/master/pagamentos'
      path: '/pagamentos'
      fullPath: '/master/pagamentos'
      preLoaderRoute: typeof MasterPagamentosRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/inadimplentes': {
      id: '/master/inadimplentes'
      path: '/inadimplentes'
      fullPath: '/master/inadimplentes'
      preLoaderRoute: typeof MasterInadimplentesRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/empresas': {
      id: '/master/empresas'
      path: '/empresas'
      fullPath: '/master/empresas'
      preLoaderRoute: typeof MasterEmpresasRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/cupons': {
      id: '/master/cupons'
      path: '/cupons'
      fullPath: '/master/cupons'
      preLoaderRoute: typeof MasterCuponsRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/configuracoes': {
      id: '/master/configuracoes'
      path: '/configuracoes'
      fullPath: '/master/configuracoes'
      preLoaderRoute: typeof MasterConfiguracoesRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/assinaturas': {
      id: '/master/assinaturas'
      path: '/assinaturas'
      fullPath: '/master/assinaturas'
      preLoaderRoute: typeof MasterAssinaturasRouteImport
      parentRoute: typeof MasterRoute
    }
    '/demo/barbearia': {
      id: '/demo/barbearia'
      path: '/barbearia'
      fullPath: '/demo/barbearia'
      preLoaderRoute: typeof DemoBarbeariaRouteImport
      parentRoute: typeof DemoRoute
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/plans': {
      id: '/billing/plans'
      path: '/billing/plans'
      fullPath: '/billing/plans'
      preLoaderRoute: typeof BillingPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/checkout': {
      id: '/billing/checkout'
      path: '/billing/checkout'
      fullPath: '/billing/checkout'
      preLoaderRoute: typeof BillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/cancel': {
      id: '/billing/cancel'
      path: '/billing/cancel'
      fullPath: '/billing/cancel'
      preLoaderRoute: typeof BillingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/$slug': {
      id: '/agendar/$slug'
      path: '/agendar/$slug'
      fullPath: '/agendar/$slug'
      preLoaderRoute: typeof AgendarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servicos': {
      id: '/admin/servicos'
      path: '/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AdminServicosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/repasses': {
      id: '/admin/repasses'
      path: '/repasses'
      fullPath: '/admin/repasses'
      preLoaderRoute: typeof AdminRepassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plano': {
      id: '/admin/plano'
      path: '/plano'
      fullPath: '/admin/plano'
      preLoaderRoute: typeof AdminPlanoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lista-espera': {
      id: '/admin/lista-espera'
      path: '/lista-espera'
      fullPath: '/admin/lista-espera'
      preLoaderRoute: typeof AdminListaEsperaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipe': {
      id: '/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AdminEquipeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comandas': {
      id: '/admin/comandas'
      path: '/comandas'
      fullPath: '/admin/comandas'
      preLoaderRoute: typeof AdminComandasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/app': {
      id: '/admin/app'
      path: '/app'
      fullPath: '/admin/app'
      preLoaderRoute: typeof AdminAppRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/convite/prestador/$token': {
      id: '/convite/prestador/$token'
      path: '/convite/prestador/$token'
      fullPath: '/convite/prestador/$token'
      preLoaderRoute: typeof ConvitePrestadorTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plano/checkout': {
      id: '/admin/plano/checkout'
      path: '/checkout'
      fullPath: '/admin/plano/checkout'
      preLoaderRoute: typeof AdminPlanoCheckoutRouteImport
      parentRoute: typeof AdminPlanoRoute
    }
  }
}

interface AdminPlanoRouteChildren {
  AdminPlanoCheckoutRoute: typeof AdminPlanoCheckoutRoute
}

const AdminPlanoRouteChildren: AdminPlanoRouteChildren = {
  AdminPlanoCheckoutRoute: AdminPlanoCheckoutRoute,
}

const AdminPlanoRouteWithChildren = AdminPlanoRoute._addFileChildren(
  AdminPlanoRouteChildren,
)

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminAppRoute: typeof AdminAppRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminComandasRoute: typeof AdminComandasRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminEquipeRoute: typeof AdminEquipeRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminListaEsperaRoute: typeof AdminListaEsperaRoute
  AdminPlanoRoute: typeof AdminPlanoRouteWithChildren
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminRepassesRoute: typeof AdminRepassesRoute
  AdminServicosRoute: typeof AdminServicosRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminAppRoute: AdminAppRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminComandasRoute: AdminComandasRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminEquipeRoute: AdminEquipeRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminListaEsperaRoute: AdminListaEsperaRoute,
  AdminPlanoRoute: AdminPlanoRouteWithChildren,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminRepassesRoute: AdminRepassesRoute,
  AdminServicosRoute: AdminServicosRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DemoRouteChildren {
  DemoBarbeariaRoute: typeof DemoBarbeariaRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoBarbeariaRoute: DemoBarbeariaRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface MasterRouteChildren {
  MasterAssinaturasRoute: typeof MasterAssinaturasRoute
  MasterConfiguracoesRoute: typeof MasterConfiguracoesRoute
  MasterCuponsRoute: typeof MasterCuponsRoute
  MasterEmpresasRoute: typeof MasterEmpresasRoute
  MasterInadimplentesRoute: typeof MasterInadimplentesRoute
  MasterPagamentosRoute: typeof MasterPagamentosRoute
  MasterPlanosRoute: typeof MasterPlanosRoute
  MasterRenovacoesRoute: typeof MasterRenovacoesRoute
  MasterSuporteRoute: typeof MasterSuporteRoute
  MasterTrafegoRoute: typeof MasterTrafegoRoute
  MasterIndexRoute: typeof MasterIndexRoute
}

const MasterRouteChildren: MasterRouteChildren = {
  MasterAssinaturasRoute: MasterAssinaturasRoute,
  MasterConfiguracoesRoute: MasterConfiguracoesRoute,
  MasterCuponsRoute: MasterCuponsRoute,
  MasterEmpresasRoute: MasterEmpresasRoute,
  MasterInadimplentesRoute: MasterInadimplentesRoute,
  MasterPagamentosRoute: MasterPagamentosRoute,
  MasterPlanosRoute: MasterPlanosRoute,
  MasterRenovacoesRoute: MasterRenovacoesRoute,
  MasterSuporteRoute: MasterSuporteRoute,
  MasterTrafegoRoute: MasterTrafegoRoute,
  MasterIndexRoute: MasterIndexRoute,
}

const MasterRouteWithChildren =
  MasterRoute._addFileChildren(MasterRouteChildren)

interface OnboardingRouteChildren {
  OnboardingCompanyRoute: typeof OnboardingCompanyRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingCompanyRoute: OnboardingCompanyRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CheckoutRoute: CheckoutRoute,
  ClienteRoute: ClienteRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRouteWithChildren,
  DesafioRoute: DesafioRoute,
  EntrarRoute: EntrarRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MasterRoute: MasterRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  PagamentoRoute: PagamentoRoute,
  PlanosRoute: PlanosRoute,
  PlansRoute: PlansRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AgendarSlugRoute: AgendarSlugRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BillingCancelRoute: BillingCancelRoute,
  BillingCheckoutRoute: BillingCheckoutRoute,
  BillingPlansRoute: BillingPlansRoute,
  BillingSuccessRoute: BillingSuccessRoute,
  ConvitePrestadorTokenRoute: ConvitePrestadorTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
