/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendarSlugRouteImport } from './routes/agendar.$slug'

const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarSlugRoute = AgendarSlugRouteImport.update({
  id: '/agendar/$slug',
  path: '/agendar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRoute
  '/entrar': typeof EntrarRoute
  '/agendar/$slug': typeof AgendarSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRoute
  '/entrar': typeof EntrarRoute
  '/agendar/$slug': typeof AgendarSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRoute
  '/entrar': typeof EntrarRoute
  '/agendar/$slug': typeof AgendarSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cliente' | '/entrar' | '/agendar/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cliente' | '/entrar' | '/agendar/$slug'
  id: '__root__' | '/' | '/cliente' | '/entrar' | '/agendar/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClienteRoute: typeof ClienteRoute
  EntrarRoute: typeof EntrarRoute
  AgendarSlugRoute: typeof AgendarSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/$slug': {
      id: '/agendar/$slug'
      path: '/agendar/$slug'
      fullPath: '/agendar/$slug'
      preLoaderRoute: typeof AgendarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClienteRoute: ClienteRoute,
  EntrarRoute: EntrarRoute,
  AgendarSlugRoute: AgendarSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
